/**
 * generated by Xtext 2.40.0
 */
package org.gol.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.gol.GolRuntimeModule;
import org.gol.GolStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class GolIdeSetup extends GolStandaloneSetup {
  @Override
  public Injector createInjector() {
    GolRuntimeModule _golRuntimeModule = new GolRuntimeModule();
    GolIdeModule _golIdeModule = new GolIdeModule();
    return Guice.createInjector(Modules2.mixin(_golRuntimeModule, _golIdeModule));
  }
}
