/*
 * generated by Xtext 2.40.0
 */
package org.gol.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.gol.parser.antlr.internal.InternalGolParser;
import org.gol.services.GolGrammarAccess;

public class GolParser extends AbstractAntlrParser {

	@Inject
	private GolGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalGolParser createParser(XtextTokenStream stream) {
		return new InternalGolParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Game";
	}

	public GolGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GolGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
