/**
 * generated by Xtext 2.40.0
 */
package org.gol.gol;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.gol.gol.GolFactory
 * @model kind="package"
 * @generated
 */
public interface GolPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "gol";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.gol.org/Gol";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "gol";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GolPackage eINSTANCE = org.gol.gol.impl.GolPackageImpl.init();

  /**
   * The meta object id for the '{@link org.gol.gol.impl.GameImpl <em>Game</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.gol.gol.impl.GameImpl
   * @see org.gol.gol.impl.GolPackageImpl#getGame()
   * @generated
   */
  int GAME = 0;

  /**
   * The feature id for the '<em><b>Grid</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME__GRID = 0;

  /**
   * The feature id for the '<em><b>Rules</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME__RULES = 1;

  /**
   * The number of structural features of the '<em>Game</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.gol.gol.impl.GridImpl <em>Grid</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.gol.gol.impl.GridImpl
   * @see org.gol.gol.impl.GolPackageImpl#getGrid()
   * @generated
   */
  int GRID = 1;

  /**
   * The feature id for the '<em><b>Size</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRID__SIZE = 0;

  /**
   * The feature id for the '<em><b>Populated Cells</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRID__POPULATED_CELLS = 1;

  /**
   * The feature id for the '<em><b>Predefined Patterns</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRID__PREDEFINED_PATTERNS = 2;

  /**
   * The number of structural features of the '<em>Grid</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRID_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.gol.gol.impl.GridSizeImpl <em>Grid Size</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.gol.gol.impl.GridSizeImpl
   * @see org.gol.gol.impl.GolPackageImpl#getGridSize()
   * @generated
   */
  int GRID_SIZE = 2;

  /**
   * The feature id for the '<em><b>Height</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRID_SIZE__HEIGHT = 0;

  /**
   * The feature id for the '<em><b>Width</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRID_SIZE__WIDTH = 1;

  /**
   * The number of structural features of the '<em>Grid Size</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRID_SIZE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.gol.gol.impl.PopulatedCellImpl <em>Populated Cell</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.gol.gol.impl.PopulatedCellImpl
   * @see org.gol.gol.impl.GolPackageImpl#getPopulatedCell()
   * @generated
   */
  int POPULATED_CELL = 3;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POPULATED_CELL__X = 0;

  /**
   * The feature id for the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POPULATED_CELL__Y = 1;

  /**
   * The number of structural features of the '<em>Populated Cell</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POPULATED_CELL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.gol.gol.impl.RulesImpl <em>Rules</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.gol.gol.impl.RulesImpl
   * @see org.gol.gol.impl.GolPackageImpl#getRules()
   * @generated
   */
  int RULES = 4;

  /**
   * The feature id for the '<em><b>Rules</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULES__RULES = 0;

  /**
   * The number of structural features of the '<em>Rules</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.gol.gol.impl.ConditionImpl <em>Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.gol.gol.impl.ConditionImpl
   * @see org.gol.gol.impl.GolPackageImpl#getCondition()
   * @generated
   */
  int CONDITION = 5;

  /**
   * The feature id for the '<em><b>Bool Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__BOOL_OP = 0;

  /**
   * The feature id for the '<em><b>NCount</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__NCOUNT = 1;

  /**
   * The feature id for the '<em><b>Separator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__SEPARATOR = 2;

  /**
   * The number of structural features of the '<em>Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.gol.gol.impl.RuleImpl <em>Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.gol.gol.impl.RuleImpl
   * @see org.gol.gol.impl.GolPackageImpl#getRule()
   * @generated
   */
  int RULE = 6;

  /**
   * The feature id for the '<em><b>State</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__STATE = 0;

  /**
   * The feature id for the '<em><b>Conditions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__CONDITIONS = 1;

  /**
   * The feature id for the '<em><b>Result</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__RESULT = 2;

  /**
   * The number of structural features of the '<em>Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_FEATURE_COUNT = 3;


  /**
   * Returns the meta object for class '{@link org.gol.gol.Game <em>Game</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Game</em>'.
   * @see org.gol.gol.Game
   * @generated
   */
  EClass getGame();

  /**
   * Returns the meta object for the containment reference '{@link org.gol.gol.Game#getGrid <em>Grid</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Grid</em>'.
   * @see org.gol.gol.Game#getGrid()
   * @see #getGame()
   * @generated
   */
  EReference getGame_Grid();

  /**
   * Returns the meta object for the containment reference '{@link org.gol.gol.Game#getRules <em>Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rules</em>'.
   * @see org.gol.gol.Game#getRules()
   * @see #getGame()
   * @generated
   */
  EReference getGame_Rules();

  /**
   * Returns the meta object for class '{@link org.gol.gol.Grid <em>Grid</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Grid</em>'.
   * @see org.gol.gol.Grid
   * @generated
   */
  EClass getGrid();

  /**
   * Returns the meta object for the containment reference '{@link org.gol.gol.Grid#getSize <em>Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Size</em>'.
   * @see org.gol.gol.Grid#getSize()
   * @see #getGrid()
   * @generated
   */
  EReference getGrid_Size();

  /**
   * Returns the meta object for the containment reference list '{@link org.gol.gol.Grid#getPopulatedCells <em>Populated Cells</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Populated Cells</em>'.
   * @see org.gol.gol.Grid#getPopulatedCells()
   * @see #getGrid()
   * @generated
   */
  EReference getGrid_PopulatedCells();

  /**
   * Returns the meta object for the attribute list '{@link org.gol.gol.Grid#getPredefinedPatterns <em>Predefined Patterns</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Predefined Patterns</em>'.
   * @see org.gol.gol.Grid#getPredefinedPatterns()
   * @see #getGrid()
   * @generated
   */
  EAttribute getGrid_PredefinedPatterns();

  /**
   * Returns the meta object for class '{@link org.gol.gol.GridSize <em>Grid Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Grid Size</em>'.
   * @see org.gol.gol.GridSize
   * @generated
   */
  EClass getGridSize();

  /**
   * Returns the meta object for the attribute '{@link org.gol.gol.GridSize#getHeight <em>Height</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Height</em>'.
   * @see org.gol.gol.GridSize#getHeight()
   * @see #getGridSize()
   * @generated
   */
  EAttribute getGridSize_Height();

  /**
   * Returns the meta object for the attribute '{@link org.gol.gol.GridSize#getWidth <em>Width</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Width</em>'.
   * @see org.gol.gol.GridSize#getWidth()
   * @see #getGridSize()
   * @generated
   */
  EAttribute getGridSize_Width();

  /**
   * Returns the meta object for class '{@link org.gol.gol.PopulatedCell <em>Populated Cell</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Populated Cell</em>'.
   * @see org.gol.gol.PopulatedCell
   * @generated
   */
  EClass getPopulatedCell();

  /**
   * Returns the meta object for the attribute '{@link org.gol.gol.PopulatedCell#getX <em>X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X</em>'.
   * @see org.gol.gol.PopulatedCell#getX()
   * @see #getPopulatedCell()
   * @generated
   */
  EAttribute getPopulatedCell_X();

  /**
   * Returns the meta object for the attribute '{@link org.gol.gol.PopulatedCell#getY <em>Y</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Y</em>'.
   * @see org.gol.gol.PopulatedCell#getY()
   * @see #getPopulatedCell()
   * @generated
   */
  EAttribute getPopulatedCell_Y();

  /**
   * Returns the meta object for class '{@link org.gol.gol.Rules <em>Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rules</em>'.
   * @see org.gol.gol.Rules
   * @generated
   */
  EClass getRules();

  /**
   * Returns the meta object for the containment reference list '{@link org.gol.gol.Rules#getRules <em>Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rules</em>'.
   * @see org.gol.gol.Rules#getRules()
   * @see #getRules()
   * @generated
   */
  EReference getRules_Rules();

  /**
   * Returns the meta object for class '{@link org.gol.gol.Condition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Condition</em>'.
   * @see org.gol.gol.Condition
   * @generated
   */
  EClass getCondition();

  /**
   * Returns the meta object for the attribute '{@link org.gol.gol.Condition#getBoolOp <em>Bool Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Bool Op</em>'.
   * @see org.gol.gol.Condition#getBoolOp()
   * @see #getCondition()
   * @generated
   */
  EAttribute getCondition_BoolOp();

  /**
   * Returns the meta object for the attribute '{@link org.gol.gol.Condition#getNCount <em>NCount</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>NCount</em>'.
   * @see org.gol.gol.Condition#getNCount()
   * @see #getCondition()
   * @generated
   */
  EAttribute getCondition_NCount();

  /**
   * Returns the meta object for the attribute '{@link org.gol.gol.Condition#getSeparator <em>Separator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Separator</em>'.
   * @see org.gol.gol.Condition#getSeparator()
   * @see #getCondition()
   * @generated
   */
  EAttribute getCondition_Separator();

  /**
   * Returns the meta object for class '{@link org.gol.gol.Rule <em>Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule</em>'.
   * @see org.gol.gol.Rule
   * @generated
   */
  EClass getRule();

  /**
   * Returns the meta object for the attribute '{@link org.gol.gol.Rule#getState <em>State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>State</em>'.
   * @see org.gol.gol.Rule#getState()
   * @see #getRule()
   * @generated
   */
  EAttribute getRule_State();

  /**
   * Returns the meta object for the containment reference list '{@link org.gol.gol.Rule#getConditions <em>Conditions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Conditions</em>'.
   * @see org.gol.gol.Rule#getConditions()
   * @see #getRule()
   * @generated
   */
  EReference getRule_Conditions();

  /**
   * Returns the meta object for the attribute '{@link org.gol.gol.Rule#getResult <em>Result</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Result</em>'.
   * @see org.gol.gol.Rule#getResult()
   * @see #getRule()
   * @generated
   */
  EAttribute getRule_Result();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  GolFactory getGolFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.gol.gol.impl.GameImpl <em>Game</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.gol.gol.impl.GameImpl
     * @see org.gol.gol.impl.GolPackageImpl#getGame()
     * @generated
     */
    EClass GAME = eINSTANCE.getGame();

    /**
     * The meta object literal for the '<em><b>Grid</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME__GRID = eINSTANCE.getGame_Grid();

    /**
     * The meta object literal for the '<em><b>Rules</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME__RULES = eINSTANCE.getGame_Rules();

    /**
     * The meta object literal for the '{@link org.gol.gol.impl.GridImpl <em>Grid</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.gol.gol.impl.GridImpl
     * @see org.gol.gol.impl.GolPackageImpl#getGrid()
     * @generated
     */
    EClass GRID = eINSTANCE.getGrid();

    /**
     * The meta object literal for the '<em><b>Size</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GRID__SIZE = eINSTANCE.getGrid_Size();

    /**
     * The meta object literal for the '<em><b>Populated Cells</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GRID__POPULATED_CELLS = eINSTANCE.getGrid_PopulatedCells();

    /**
     * The meta object literal for the '<em><b>Predefined Patterns</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GRID__PREDEFINED_PATTERNS = eINSTANCE.getGrid_PredefinedPatterns();

    /**
     * The meta object literal for the '{@link org.gol.gol.impl.GridSizeImpl <em>Grid Size</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.gol.gol.impl.GridSizeImpl
     * @see org.gol.gol.impl.GolPackageImpl#getGridSize()
     * @generated
     */
    EClass GRID_SIZE = eINSTANCE.getGridSize();

    /**
     * The meta object literal for the '<em><b>Height</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GRID_SIZE__HEIGHT = eINSTANCE.getGridSize_Height();

    /**
     * The meta object literal for the '<em><b>Width</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GRID_SIZE__WIDTH = eINSTANCE.getGridSize_Width();

    /**
     * The meta object literal for the '{@link org.gol.gol.impl.PopulatedCellImpl <em>Populated Cell</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.gol.gol.impl.PopulatedCellImpl
     * @see org.gol.gol.impl.GolPackageImpl#getPopulatedCell()
     * @generated
     */
    EClass POPULATED_CELL = eINSTANCE.getPopulatedCell();

    /**
     * The meta object literal for the '<em><b>X</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute POPULATED_CELL__X = eINSTANCE.getPopulatedCell_X();

    /**
     * The meta object literal for the '<em><b>Y</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute POPULATED_CELL__Y = eINSTANCE.getPopulatedCell_Y();

    /**
     * The meta object literal for the '{@link org.gol.gol.impl.RulesImpl <em>Rules</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.gol.gol.impl.RulesImpl
     * @see org.gol.gol.impl.GolPackageImpl#getRules()
     * @generated
     */
    EClass RULES = eINSTANCE.getRules();

    /**
     * The meta object literal for the '<em><b>Rules</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULES__RULES = eINSTANCE.getRules_Rules();

    /**
     * The meta object literal for the '{@link org.gol.gol.impl.ConditionImpl <em>Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.gol.gol.impl.ConditionImpl
     * @see org.gol.gol.impl.GolPackageImpl#getCondition()
     * @generated
     */
    EClass CONDITION = eINSTANCE.getCondition();

    /**
     * The meta object literal for the '<em><b>Bool Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITION__BOOL_OP = eINSTANCE.getCondition_BoolOp();

    /**
     * The meta object literal for the '<em><b>NCount</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITION__NCOUNT = eINSTANCE.getCondition_NCount();

    /**
     * The meta object literal for the '<em><b>Separator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITION__SEPARATOR = eINSTANCE.getCondition_Separator();

    /**
     * The meta object literal for the '{@link org.gol.gol.impl.RuleImpl <em>Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.gol.gol.impl.RuleImpl
     * @see org.gol.gol.impl.GolPackageImpl#getRule()
     * @generated
     */
    EClass RULE = eINSTANCE.getRule();

    /**
     * The meta object literal for the '<em><b>State</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE__STATE = eINSTANCE.getRule_State();

    /**
     * The meta object literal for the '<em><b>Conditions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE__CONDITIONS = eINSTANCE.getRule_Conditions();

    /**
     * The meta object literal for the '<em><b>Result</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE__RESULT = eINSTANCE.getRule_Result();

  }

} //GolPackage
