/**
 * generated by Xtext 2.40.0
 */
package org.gol.gol;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Grid</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.gol.gol.Grid#getSize <em>Size</em>}</li>
 *   <li>{@link org.gol.gol.Grid#getPopulatedCells <em>Populated Cells</em>}</li>
 *   <li>{@link org.gol.gol.Grid#getPredefinedPatterns <em>Predefined Patterns</em>}</li>
 * </ul>
 *
 * @see org.gol.gol.GolPackage#getGrid()
 * @model
 * @generated
 */
public interface Grid extends EObject
{
  /**
   * Returns the value of the '<em><b>Size</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Size</em>' containment reference.
   * @see #setSize(GridSize)
   * @see org.gol.gol.GolPackage#getGrid_Size()
   * @model containment="true"
   * @generated
   */
  GridSize getSize();

  /**
   * Sets the value of the '{@link org.gol.gol.Grid#getSize <em>Size</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Size</em>' containment reference.
   * @see #getSize()
   * @generated
   */
  void setSize(GridSize value);

  /**
   * Returns the value of the '<em><b>Populated Cells</b></em>' containment reference list.
   * The list contents are of type {@link org.gol.gol.PopulatedCell}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Populated Cells</em>' containment reference list.
   * @see org.gol.gol.GolPackage#getGrid_PopulatedCells()
   * @model containment="true"
   * @generated
   */
  EList<PopulatedCell> getPopulatedCells();

  /**
   * Returns the value of the '<em><b>Predefined Patterns</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Predefined Patterns</em>' attribute list.
   * @see org.gol.gol.GolPackage#getGrid_PredefinedPatterns()
   * @model unique="false"
   * @generated
   */
  EList<String> getPredefinedPatterns();

} // Grid
