/**
 * generated by Xtext 2.40.0
 */
package org.gol.gol;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Populated Cell</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.gol.gol.PopulatedCell#getX <em>X</em>}</li>
 *   <li>{@link org.gol.gol.PopulatedCell#getY <em>Y</em>}</li>
 * </ul>
 *
 * @see org.gol.gol.GolPackage#getPopulatedCell()
 * @model
 * @generated
 */
public interface PopulatedCell extends EObject
{
  /**
   * Returns the value of the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>X</em>' attribute.
   * @see #setX(int)
   * @see org.gol.gol.GolPackage#getPopulatedCell_X()
   * @model
   * @generated
   */
  int getX();

  /**
   * Sets the value of the '{@link org.gol.gol.PopulatedCell#getX <em>X</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>X</em>' attribute.
   * @see #getX()
   * @generated
   */
  void setX(int value);

  /**
   * Returns the value of the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Y</em>' attribute.
   * @see #setY(int)
   * @see org.gol.gol.GolPackage#getPopulatedCell_Y()
   * @model
   * @generated
   */
  int getY();

  /**
   * Sets the value of the '{@link org.gol.gol.PopulatedCell#getY <em>Y</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Y</em>' attribute.
   * @see #getY()
   * @generated
   */
  void setY(int value);

} // PopulatedCell
