/**
 * generated by Xtext 2.40.0
 */
package org.gol.gol;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rules</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.gol.gol.Rules#getRules <em>Rules</em>}</li>
 * </ul>
 *
 * @see org.gol.gol.GolPackage#getRules()
 * @model
 * @generated
 */
public interface Rules extends EObject
{
  /**
   * Returns the value of the '<em><b>Rules</b></em>' containment reference list.
   * The list contents are of type {@link org.gol.gol.Rule}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rules</em>' containment reference list.
   * @see org.gol.gol.GolPackage#getRules_Rules()
   * @model containment="true"
   * @generated
   */
  EList<Rule> getRules();

} // Rules
