/*
 * generated by Xtext 2.40.0
 */
package org.gol.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGolScopeProvider extends DelegatingScopeProvider {
}
