/**
 * generated by Xtext 2.40.0
 */
package org.gol.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class GolUiModule extends AbstractGolUiModule {
  public GolUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
