/*
 * generated by Xtext 2.40.0
 */
package org.gol.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;
import org.eclipse.xtext.validation.ComposedChecks;
import org.eclipse.xtext.validation.GolValidator;

@ComposedChecks(validators = {GolValidator.class})
public abstract class AbstractGolValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.gol.gol.GolPackage.eINSTANCE);
		return result;
	}
}
