/*
 * generated by Xtext 2.40.0
 */
package org.gol.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.gol.ui.internal.GolActivator;

public class GolUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return GolActivator.getInstance().getInjector("org.gol.Gol");
	}

}
