/**
 * generated by Xtext 2.40.0
 */
package org.gol;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class GolRuntimeModule extends AbstractGolRuntimeModule {
}
