/**
 * generated by Xtext 2.40.0
 */
package org.gol;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class GolStandaloneSetup extends GolStandaloneSetupGenerated {
  public static void doSetup() {
    new GolStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
