/*
 * generated by Xtext 2.40.0
 */
package org.gol.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.gol.GolRuntimeModule
import org.gol.GolStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class GolIdeSetup extends GolStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new GolRuntimeModule, new GolIdeModule))
	}
	
}
